/**
 * Marked-up chart captures of a real trade, bound to its position_id.
 *
 * MetaTrader knows where you entered and where you left. It has no picture of
 * what the chart looked like, and a trade you cannot see again is a trade you
 * cannot review. This takes a trade from the read-only bridge, marks it on the
 * TradingView chart, screenshots it, and tells the journal the image exists.
 *
 * ---------------------------------------------------------------------------
 * The thing that would ruin it
 * ---------------------------------------------------------------------------
 *
 * A screenshot taken after the trade closed shows the bars that came *after*
 * the entry. As a record of the outcome that is fine. As a way to review the
 * entry *decision* it is worthless, because it contains the answer — and worse
 * than worthless, because it feels like review. Enough of those and you have
 * built a machine for hindsight bias.
 *
 * So there are two kinds, and `entry` is the one with rules:
 *
 *   entry    Everything that was knowable when you entered, and nothing else.
 *   review   The whole trade, entry through exit. The outcome is the subject.
 *
 * Four things leak the future into an entry frame. Only the first is obvious,
 * and the last two were not obvious at all:
 *
 *   1. The visible range. Ends at the entry bar. `planCapture` computes it and
 *      a test asserts no shape and no edge of the window sits past it.
 *
 *   2. Exit markup. Not drawn at all for an entry capture — not the exit line,
 *      not the P&L, not the exit reason in the label.
 *
 *   3. The timeframe. Choosing it from the trade's *duration* — sensible for a
 *      review — tells the reader how long the trade lasted before they have
 *      looked at a single candle. Duration is an outcome. Entry captures use a
 *      fixed timeframe unless you name one.
 *
 *   4. Stop and target levels inferred from the exit fill. `stopsize.py` makes
 *      the useful observation that a trade closed at stop loss exits *at* the
 *      stop, which recovers a level MT5 never stored. That inference is sound,
 *      and it is still inadmissible here: it only produces a level for trades
 *      that were stopped out, so the mere presence of a stop rectangle on an
 *      entry frame would tell you the trade lost. An entry capture draws
 *      levels only from a source independent of the outcome — a stop you pass
 *      in, from the plan, the journal or order history — and says so in its
 *      notes when it has none.
 *
 * ---------------------------------------------------------------------------
 * Two smaller things
 * ---------------------------------------------------------------------------
 *
 * There is no long/short position widget in `draw_shape`, so risk and reward
 * are drawn as rectangles from entry to stop and entry to target.
 *
 * TradingView's prices are not your broker's. Every capture carries the note;
 * see PRICE_SOURCE_NOTE in symbolmap.js for what that means for reading one.
 *
 * Captures are a **cache, not an archive**: a pure function of trade data plus
 * chart settings, so deleting one loses nothing that cannot be regenerated by
 * calling this again. Retention lives in the journal (`POST /prune`), which
 * deletes files and keeps the rows.
 */
import * as _chart from './chart.js';
import * as _drawing from './drawing.js';
import * as _capture from './capture.js';
import * as _mt5 from './mt5.js';
import * as _journal from './journal.js';
import { mapSymbol, loadOverrides as _loadOverrides, PRICE_SOURCE_NOTE } from './symbolmap.js';

export const TIMEFRAME_SECONDS = {
  '1': 60, '3': 180, '5': 300, '15': 900, '30': 1800,
  '60': 3600, '120': 7200, '240': 14400, 'D': 86400, 'W': 604800,
};

/**
 * The timeframe an entry capture uses when you do not name one.
 *
 * Fixed on purpose — see leak 3 above. Five minutes is a compromise that shows
 * an intraday setup's structure without collapsing a swing entry into noise;
 * pass `timeframe` when it is the wrong one for how you actually trade.
 */
export const ENTRY_TIMEFRAME = '5';

/** A review should span enough bars to read, without the trade becoming a dot. */
const REVIEW_TARGET_BARS = 60;
const TIMEFRAME_ORDER = ['1', '3', '5', '15', '30', '60', '120', '240', 'D', 'W'];

const DEFAULT_BARS_BEFORE = { entry: 120, review: 40 };
const DEFAULT_BARS_AFTER = 20;

const COLOR = {
  entry: '#2962FF',
  stop: '#F23645',
  target: '#089981',
  exit: '#FF9800',
  label: '#787B86',
};

export const NO_STOP_NOTE =
  'No stop level was supplied, so none is drawn. A stop read back from the exit ' +
  'fill exists only for trades that were stopped out, so drawing one would make ' +
  'its presence a hint about the outcome.';

export function timeframeSeconds(timeframe) {
  const key = String(timeframe ?? '').trim().toUpperCase();
  const seconds = TIMEFRAME_SECONDS[key];
  if (!seconds) {
    throw new Error(
      `Unknown timeframe "${timeframe}". Use one of: ${Object.keys(TIMEFRAME_SECONDS).join(', ')}`);
  }
  return seconds;
}

/** The open time of the bar containing `ts`. Bar times are open times. */
export function barOpen(ts, tfSeconds) {
  return Math.floor(ts / tfSeconds) * tfSeconds;
}

/**
 * Pick a timeframe that shows the trade at a readable size.
 *
 * For **review captures only**. Deriving this for an entry capture would put
 * the trade's duration into the frame before the reader has looked at a
 * candle — see leak 3.
 */
export function chooseTimeframe(durationSec) {
  if (!Number.isFinite(durationSec) || durationSec <= 0) return ENTRY_TIMEFRAME;
  for (const tf of TIMEFRAME_ORDER) {
    if (durationSec / TIMEFRAME_SECONDS[tf] <= REVIEW_TARGET_BARS) return tf;
  }
  return 'W';
}

/**
 * Where the stop and target came from, and whether they may be drawn.
 *
 * Supplied levels are admissible everywhere: they were known before the trade
 * resolved. Levels read back from the exit fill are admissible on a review
 * only — see leak 4.
 */
export function deriveLevels({ trade, kind, stop, target }) {
  const out = { stop: null, target: null, notes: [] };

  if (stop !== undefined && stop !== null && stop !== '') {
    out.stop = { price: Number(stop), source: 'supplied' };
  }
  if (target !== undefined && target !== null && target !== '') {
    out.target = { price: Number(target), source: 'supplied' };
  }

  if (kind === 'entry') {
    if (!out.stop) out.notes.push(NO_STOP_NOTE);
    return out;
  }

  const exitPrice = trade?.exit_price;
  if (!out.stop && trade?.exit_reason === 'stop_loss' && exitPrice != null) {
    out.stop = { price: Number(exitPrice), source: 'exit_fill' };
    out.notes.push('Stop read back from the exit fill: a stop-loss close happens at the stop.');
  }
  if (!out.target && trade?.exit_reason === 'take_profit' && exitPrice != null) {
    out.target = { price: Number(exitPrice), source: 'exit_fill' };
    out.notes.push('Target read back from the exit fill: a take-profit close happens at the target.');
  }
  return out;
}

function round(value, digits = 5) {
  return Number.isFinite(value) ? Number(value.toFixed(digits)) : value;
}

function stamp(unixSeconds) {
  return new Date(unixSeconds * 1000).toISOString().slice(0, 19).replace(/[-:]/g, '').replace('T', '-');
}

/**
 * Everything about a capture that can be decided without touching the chart.
 *
 * Pure, so the guarantee that matters — an entry frame contains nothing from
 * after the entry — is a property of a value a test can inspect, rather than
 * something that has to be true of a screenshot.
 */
export function planCapture({
  trade, kind = 'entry', symbol, timeframe, barsBefore, barsAfter,
  stop, target, includeEntryBar = true, now,
} = {}) {
  if (kind !== 'entry' && kind !== 'review') {
    throw new Error(`Unknown capture kind "${kind}". Use "entry" or "review".`);
  }
  if (!trade || trade.position_id === undefined || trade.position_id === null) {
    throw new Error('planCapture needs a trade with a position_id');
  }
  if (!Number.isFinite(trade.opened_utc)) {
    throw new Error(
      `Trade ${trade.position_id} has no entry time. A window that starts mid-position ` +
      'reports entry_missing rather than inventing one — widen the window with days=.');
  }
  if (!Number.isFinite(trade.entry_price)) {
    throw new Error(
      `Trade ${trade.position_id} has no entry price (entry_missing=${!!trade.entry_missing}). ` +
      'There is nothing to mark.');
  }

  const capturedAt = Number.isFinite(now) ? now : Math.floor(Date.now() / 1000);

  // Leak 3: duration only chooses a timeframe for a review.
  const resolvedTimeframe = timeframe
    || (kind === 'review' ? chooseTimeframe(trade.duration_sec) : ENTRY_TIMEFRAME);
  const tf = timeframeSeconds(resolvedTimeframe);

  const entryBar = barOpen(trade.opened_utc, tf);
  // At least one bar of context either side: a zero-width or inverted range is
  // not a tighter frame, it is a chart command that does nothing useful.
  const before = Math.max(1, Number.isFinite(barsBefore) ? barsBefore : DEFAULT_BARS_BEFORE[kind]);
  const after = Math.max(0, Number.isFinite(barsAfter) ? barsAfter : DEFAULT_BARS_AFTER);

  const warnings = [PRICE_SOURCE_NOTE];
  const notes = [];

  // Leak 1: the right edge.
  let to;
  if (kind === 'entry') {
    to = includeEntryBar ? entryBar : entryBar - 1;
    notes.push(includeEntryBar
      ? 'Frame ends at the entry bar. Nothing after it is visible — though the ' +
        'entry bar itself finished forming after you were in, so its close is ' +
        'the one piece of the picture you did not have.'
      : 'Frame ends one bar before the entry bar: every candle shown had closed ' +
        'before the entry.');
  } else {
    const closedAt = Number.isFinite(trade.closed_utc) ? trade.closed_utc : capturedAt;
    to = barOpen(closedAt, tf) + after * tf;
    if (!Number.isFinite(trade.closed_utc)) {
      notes.push('Position is still open — the frame runs to now, and there is no exit to mark.');
    }
  }
  const from = entryBar - before * tf;

  const levels = deriveLevels({ trade, kind, stop, target });
  notes.push(...levels.notes);

  const direction = trade.direction || null;
  const shapes = [];

  // The entry, on both kinds.
  shapes.push({
    role: 'entry_line',
    shape: 'horizontal_line',
    point: { time: entryBar, price: trade.entry_price },
    text: `Entry ${trade.entry_price}${direction ? ` (${direction})` : ''}`,
    overrides: { linecolor: COLOR.entry, linewidth: 2, showLabel: true },
  });
  shapes.push({
    role: 'entry_marker',
    shape: 'vertical_line',
    point: { time: entryBar, price: trade.entry_price },
    overrides: { linecolor: COLOR.entry, linewidth: 1, linestyle: 2 },
  });

  // Risk and reward as rectangles: there is no position widget in draw_shape.
  if (levels.stop) {
    shapes.push({
      role: 'stop_zone',
      shape: 'rectangle',
      point: { time: entryBar, price: trade.entry_price },
      point2: { time: to, price: levels.stop.price },
      overrides: {
        color: COLOR.stop, backgroundColor: COLOR.stop, transparency: 85, linewidth: 1,
      },
    });
  }
  if (levels.target) {
    shapes.push({
      role: 'target_zone',
      shape: 'rectangle',
      point: { time: entryBar, price: trade.entry_price },
      point2: { time: to, price: levels.target.price },
      overrides: {
        color: COLOR.target, backgroundColor: COLOR.target, transparency: 85, linewidth: 1,
      },
    });
  }

  // Leak 2: nothing about the exit reaches an entry frame.
  if (kind === 'review' && Number.isFinite(trade.closed_utc) && trade.exit_price != null) {
    const exitBar = barOpen(trade.closed_utc, tf);
    shapes.push({
      role: 'exit_line',
      shape: 'horizontal_line',
      point: { time: exitBar, price: trade.exit_price },
      text: `Exit ${trade.exit_price}${trade.exit_reason ? ` (${trade.exit_reason})` : ''}`,
      overrides: { linecolor: COLOR.exit, linewidth: 2, showLabel: true },
    });
    shapes.push({
      role: 'exit_marker',
      shape: 'vertical_line',
      point: { time: exitBar, price: trade.exit_price },
      overrides: { linecolor: COLOR.exit, linewidth: 1, linestyle: 2 },
    });
  }

  const header = [
    `${trade.symbol || '?'} → ${symbol || '?'}`,
    direction,
    `entry ${trade.entry_price}`,
  ].filter(Boolean).join(' · ');
  const outcome = kind === 'review'
    ? [
      trade.exit_price != null ? `exit ${trade.exit_price}` : 'open',
      trade.exit_reason || null,
      trade.net != null ? `net ${trade.net}` : null,
    ].filter(Boolean).join(' · ')
    : 'entry frame — nothing after the entry is shown';

  shapes.push({
    role: 'label',
    shape: 'text',
    point: { time: from + 2 * tf, price: trade.entry_price },
    text: `${header}\n${outcome}\n${PRICE_SOURCE_NOTE}`,
    overrides: { color: COLOR.label, fontsize: 12, bold: false },
  });

  return {
    kind,
    position_id: String(trade.position_id),
    broker_symbol: trade.symbol || null,
    symbol: symbol || null,
    direction,
    timeframe: String(resolvedTimeframe),
    timeframe_source: timeframe ? 'requested'
      : (kind === 'review' ? 'derived_from_duration' : 'fixed_default'),
    range: { from, to },
    entry_bar: entryBar,
    levels: {
      entry: round(trade.entry_price),
      stop: levels.stop ? { ...levels.stop, price: round(levels.stop.price) } : null,
      target: levels.target ? { ...levels.target, price: round(levels.target.price) } : null,
      exit: kind === 'review' && trade.exit_price != null ? round(trade.exit_price) : null,
    },
    shapes,
    filename: `trade_${trade.position_id}_${kind}_${stamp(capturedAt)}`,
    warnings,
    notes,
  };
}

function _resolve(deps) {
  return {
    chart: deps?.chart || _chart,
    drawing: deps?.drawing || _drawing,
    capture: deps?.capture || _capture,
    mt5: deps?.mt5 || _mt5,
    journal: deps?.journal || _journal,
    loadOverrides: deps?.loadOverrides || _loadOverrides,
    now: deps?.now || (() => Math.floor(Date.now() / 1000)),
  };
}

/**
 * Find one trade in the bridge's paired-trade history.
 *
 * With no position_id, the most recently *closed* trade is the one you almost
 * always mean — you just finished it and want to look at it.
 */
export async function findTrade({ position_id, symbol, from, to, days = 30, _deps } = {}) {
  const { mt5, now } = _resolve(_deps);
  const end = Number.isFinite(to) ? to : now();
  const start = Number.isFinite(from) ? from : end - days * 86400;

  const result = await mt5.trades({
    from: start, to: end, symbol, summary: false, limit: 1000,
  });
  const rows = result?.trades || [];
  const window = `${new Date(start * 1000).toISOString().slice(0, 10)} → ` +
    `${new Date(end * 1000).toISOString().slice(0, 10)}`;

  if (!rows.length) {
    throw new Error(`No trades in ${window}. Widen the window with days=.`);
  }

  if (position_id === undefined || position_id === null || position_id === '') {
    const closed = rows.filter(t => !t.open && Number.isFinite(t.closed_utc));
    if (closed.length) {
      return closed.reduce((latest, row) => (row.closed_utc > latest.closed_utc ? row : latest));
    }
    // Nothing closed in the window: fall back to the most recently opened.
    return rows[rows.length - 1];
  }

  const wanted = String(position_id);
  const found = rows.find(t => String(t.position_id) === wanted);
  if (!found) {
    throw new Error(
      `Position ${wanted} is not among the ${rows.length} trades in ${window}. ` +
      'Widen the window with days=, or check the id with mt5_trades.');
  }
  return found;
}

/**
 * Capture one trade: resolve it, mark it, shoot it, file it.
 *
 * The markup is removed again afterwards. A capture that left its rectangles
 * behind would accumulate on the user's own chart, and the next capture would
 * photograph the last one — so only the shapes this call created are removed,
 * by id, leaving anything the user drew alone.
 */
export async function captureTrade({
  position_id, kind = 'entry', symbol, timeframe, days = 30, from, to,
  stop, target, bars_before, bars_after, include_entry_bar = true,
  attach = true, keep_drawings = false, _deps,
} = {}) {
  const deps = _resolve(_deps);
  const trade = await findTrade({ position_id, from, to, days, _deps });

  let tvSymbol = symbol;
  let mapping = null;
  if (!tvSymbol) {
    const { overrides } = deps.loadOverrides();
    mapping = mapSymbol(trade.symbol, { overrides });
    if (!mapping.success) throw new Error(`${mapping.reason} ${mapping.hint}`);
    tvSymbol = mapping.symbol;
  }

  const plan = planCapture({
    trade, kind, symbol: tvSymbol, timeframe,
    barsBefore: bars_before, barsAfter: bars_after,
    stop, target, includeEntryBar: include_entry_bar,
    now: deps.now(),
  });

  await deps.chart.setSymbol({ symbol: plan.symbol, _deps });
  await deps.chart.setTimeframe({ timeframe: plan.timeframe, _deps });
  await deps.chart.setVisibleRange({ from: plan.range.from, to: plan.range.to, _deps });

  const drawn = [];
  const shapeErrors = [];
  for (const shape of plan.shapes) {
    try {
      const result = await deps.drawing.drawShape({
        shape: shape.shape, point: shape.point, point2: shape.point2,
        overrides: shape.overrides, text: shape.text, _deps,
      });
      if (result?.entity_id) drawn.push({ role: shape.role, entity_id: result.entity_id });
    } catch (err) {
      // One failed rectangle should not cost the whole capture, but it must
      // not vanish either: a missing stop zone is indistinguishable from a
      // trade that had no stop.
      shapeErrors.push({ role: shape.role, error: err.message });
    }
  }

  let capture;
  try {
    capture = await deps.capture.captureScreenshot({
      region: 'chart', filename: plan.filename, waitForRender: true,
    });
  } finally {
    if (!keep_drawings) {
      for (const { entity_id } of drawn) {
        try {
          await deps.drawing.removeOne({ entity_id, _deps });
        } catch {
          // The picture is already taken; a leftover shape is not worth failing on.
        }
      }
    }
  }

  const filePath = capture?.file_path || null;
  let attached = { ok: false, skipped: true };
  if (attach && filePath) {
    try {
      const result = await deps.journal.attachScreenshot({
        path: filePath, kind: `trade_${plan.kind}`, position_id: plan.position_id, _deps,
      });
      attached = { ok: true, skipped: false, id: result?.id ?? null };
    } catch (err) {
      // The image exists on disk either way. A journal that is not running is
      // a missing index entry, not a lost capture.
      attached = { ok: false, skipped: false, error: err.message };
    }
  }

  return {
    success: true,
    kind: plan.kind,
    position_id: plan.position_id,
    broker_symbol: plan.broker_symbol,
    symbol: plan.symbol,
    symbol_mapping: mapping ? { via: mapping.via, root: mapping.root } : { via: 'requested' },
    direction: plan.direction,
    timeframe: plan.timeframe,
    timeframe_source: plan.timeframe_source,
    range: plan.range,
    levels: plan.levels,
    file_path: filePath,
    drawings: { created: drawn.length, removed: keep_drawings ? 0 : drawn.length },
    ...(shapeErrors.length ? { shape_errors: shapeErrors } : {}),
    journal: attached,
    warnings: plan.warnings,
    notes: plan.notes,
  };
}
